# Generated by Django 5.1.3 on 2025-02-01 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(message='Телефон в формате +79001234567', regex='^\\+7\\d{8,12}$')], verbose_name='Телефон')),
                ('fio', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('city', models.CharField(blank=True, default='г Воронеж', max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Улица')),
                ('home', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Квартира')),
                ('entrance', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Подъезд')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('organization', models.BooleanField(default=False, verbose_name='Организация?')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
