# Generated by Django 5.1.3 on 2025-02-07 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_historicalproductorder_allowance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус')),
                ('opening_time', models.DateTimeField(auto_now_add=True, verbose_name='Время открытия')),
                ('closing_time', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('initial_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начальная сумма наличных')),
                ('final_cash', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Конечная сумма наличных')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Общая выручка')),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Выручка наличными')),
                ('total_non_cash', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Выручка безналичными')),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Общая сумма возвратов')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Общий расход наличных')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('org_transfer', 'Перевод организации')], max_length=20, verbose_name='Способ оплаты')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='orders.order', verbose_name='Заказ')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cash_register.shift', verbose_name='Смена')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма возврата')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('org_transfer', 'Перевод организации')], editable=False, max_length=20, verbose_name='Способ возврата')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='cash_register.receipt', verbose_name='Чек')),
                ('shift', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='cash_register.shift', verbose_name='Смена')),
            ],
        ),
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма расхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses', to='cash_register.shift', verbose_name='Смена')),
            ],
        ),
    ]
