# Generated by Django 5.1.3 on 2025-02-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashexpense',
            name='description',
        ),
        migrations.AlterField(
            model_name='shift',
            name='initial_cash',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Начальная сумма наличных'),
        ),
    ]
