# Generated by Django 5.1.3 on 2025-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_remove_cashexpense_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма расхода'),
        ),
    ]
