# Generated by Django 5.1.3 on 2025-02-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0005_alter_receipt_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashexpense',
            options={'verbose_name': 'Наличный расход', 'verbose_name_plural': 'Наличные расходы'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
    ]
