# Generated by Django 5.1.3 on 2025-02-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0007_alter_shift_final_cash_alter_shift_initial_cash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Возврат', 'verbose_name_plural': 'Возвраты'},
        ),
    ]
