# Generated by Django 5.1.3 on 2025-02-01 10:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Короткий ворс', max_length=100, verbose_name='Название услуги')),
                ('product_long_name', models.CharField(default='Короткий ворс', max_length=100, verbose_name='Название услуги')),
                ('product_price', models.IntegerField(default=150, verbose_name='Цена')),
                ('min_amount', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Минимальное Кол-во')),
            ],
            options={
                'verbose_name': 'Услуги стирки ковров',
                'verbose_name_plural': 'Услуги стирки ковров',
            },
        ),
        migrations.CreateModel(
            name='ProductAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Запах', max_length=100, verbose_name='Название услуги')),
                ('product_long_name', models.CharField(default='Запах', max_length=100, verbose_name='Название услуги')),
                ('product_price', models.IntegerField(default=100, verbose_name='Цена')),
                ('min_amount', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Минимальное Кол-во')),
            ],
            options={
                'verbose_name': 'Доп услуги стирки ковров',
                'verbose_name_plural': 'Доп услуги стирки ковров',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_numb', models.IntegerField(blank=True, default=0, verbose_name='ID')),
                ('size_name', models.CharField(blank=True, default='Штуки', max_length=20)),
                ('size_name_short', models.CharField(blank=True, default='шт', max_length=3)),
            ],
            options={
                'verbose_name': 'Единицы измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('first_message', models.TextField(blank=True, default=None, null=True, verbose_name='Сообщение')),
                ('second_message', models.TextField(blank=True, default=None, null=True, verbose_name='Сообщение 2')),
                ('group_stage', models.IntegerField(default=0)),
                ('super_stage', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Дата время создания')),
                ('create_date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата создания')),
                ('order_number', models.CharField(editable=False, max_length=10, verbose_name='Номер заказа')),
                ('check_call', models.BooleanField(default=False, verbose_name='Позвонить')),
                ('check_stage_hide', models.IntegerField(default=1)),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Целевая дата')),
                ('order_sum', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Сумма заказа')),
                ('comment', models.TextField(blank=True, default=None, verbose_name='Комментарий')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клиент')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.stage', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(19), django.core.validators.MinValueValidator(0.1)], verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(19), django.core.validators.MinValueValidator(0.1)], verbose_name='Длина')),
                ('overlock', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Оверлок')),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Надбавка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.product', verbose_name='Наименование')),
                ('product_add', models.ManyToManyField(blank=True, default=None, related_name='product_add', to='orders.productadd', verbose_name='Доп услуги')),
            ],
            options={
                'verbose_name': 'Ковер',
                'verbose_name_plural': 'Ковры',
            },
        ),
        migrations.CreateModel(
            name='MessageProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Наименование')),
                ('product_order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mesage_order', to='orders.productorder')),
            ],
        ),
        migrations.AddField(
            model_name='productadd',
            name='product_unit',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.productunit', verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.productunit', verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='SecondProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Стирка пледа', max_length=100, verbose_name='Название услуги')),
                ('product_long_name', models.CharField(default='Стирка пледа', max_length=100, verbose_name='Название услуги')),
                ('product_price', models.IntegerField(default=100, verbose_name='Цена')),
                ('min_amount', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Минимальное Кол-во')),
                ('product_unit', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.productunit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Услуги стирки',
                'verbose_name_plural': 'Услуги стирки',
            },
        ),
        migrations.CreateModel(
            name='SecondProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_amount', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Кол-во')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.secondproduct', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Стирка',
                'verbose_name_plural': 'Стирка',
            },
        ),
    ]
