# Generated by Django 5.1.3 on 2025-02-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_historicalsecondproductorder_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrderImage',
        ),
    ]
