# Generated by Django 5.1.3 on 2025-02-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_productorderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadd',
            name='service_type',
            field=models.CharField(choices=[('usual', 'Обычная услуга'), ('overlock', 'Оверлок'), ('additional', 'Дополнительная услуга')], default='usual', max_length=20, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_long_name',
            field=models.CharField(default='Услуга', max_length=100, verbose_name='Полное название услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Услуга', max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productadd',
            name='product_long_name',
            field=models.CharField(default='Услуга', max_length=100, verbose_name='Полное название услуги'),
        ),
        migrations.AlterField(
            model_name='productadd',
            name='product_name',
            field=models.CharField(default='Услуга', max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='secondproduct',
            name='product_long_name',
            field=models.CharField(default='Услуга', max_length=100, verbose_name='Полное название услуги'),
        ),
        migrations.AlterField(
            model_name='secondproduct',
            name='product_name',
            field=models.CharField(default='Услуга', max_length=100, verbose_name='Название услуги'),
        ),
    ]
