# Generated by Django 5.1.3 on 2025-02-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productadd_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
