# Generated by Django 5.1.3 on 2025-02-07 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_historicalorder_user_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductorder',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Надбавка'),
        ),
        migrations.AlterField(
            model_name='historicalproductorder',
            name='overlock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Оверлок'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Надбавка'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='overlock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Оверлок'),
        ),
    ]
