# Generated by Django 5.1.3 on 2025-02-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_historicalproductorder_allowance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadd',
            name='service_type',
        ),
    ]
