# Generated by Django 5.1.3 on 2025-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_productadd_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagepermission',
            name='check_call_ave',
            field=models.BooleanField(default=False),
        ),
    ]
