# Generated by Django 5.1.3 on 2025-02-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_groupstagepermission_check_call_ave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstagepermission',
            old_name='check_call_ave',
            new_name='allow_call_average',
        ),
    ]
