# Generated by Django 5.1.3 on 2025-02-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_check_call_ave_groupstagepermission_allow_call_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstagepermission',
            old_name='allow_call_average',
            new_name='allow_call_status',
        ),
    ]
