# Generated by Django 5.1.3 on 2025-02-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_allow_call_average_groupstagepermission_allow_call_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstagepermission',
            options={'verbose_name': 'Доступные статусы пользователей', 'verbose_name_plural': 'Доступные статусы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Типы ковров', 'verbose_name_plural': 'Типы ковров'},
        ),
        migrations.AlterModelOptions(
            name='productadd',
            options={'verbose_name': 'Доп услуги к коврам', 'verbose_name_plural': 'Доп услуги к коврам'},
        ),
        migrations.AlterModelOptions(
            name='secondproduct',
            options={'verbose_name': 'Доп услуги', 'verbose_name_plural': 'Доп услуги'},
        ),
    ]
